/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1WorkspaceRouteImport } from './routes/api/v1/workspace'
import { Route as ApiV1AuthSplatRouteImport } from './routes/api/v1/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WorkspaceRoute = ApiV1WorkspaceRouteImport.update({
  id: '/api/v1/workspace',
  path: '/api/v1/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthSplatRoute = ApiV1AuthSplatRouteImport.update({
  id: '/api/v1/auth/$',
  path: '/api/v1/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/workspace': typeof ApiV1WorkspaceRoute
  '/api/v1/auth/$': typeof ApiV1AuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/workspace': typeof ApiV1WorkspaceRoute
  '/api/v1/auth/$': typeof ApiV1AuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/workspace': typeof ApiV1WorkspaceRoute
  '/api/v1/auth/$': typeof ApiV1AuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/api/v1/health'
    | '/api/v1/workspace'
    | '/api/v1/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/api/v1/health'
    | '/api/v1/workspace'
    | '/api/v1/auth/$'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/api/v1/health'
    | '/api/v1/workspace'
    | '/api/v1/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1WorkspaceRoute: typeof ApiV1WorkspaceRoute
  ApiV1AuthSplatRoute: typeof ApiV1AuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workspace': {
      id: '/api/v1/workspace'
      path: '/api/v1/workspace'
      fullPath: '/api/v1/workspace'
      preLoaderRoute: typeof ApiV1WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/$': {
      id: '/api/v1/auth/$'
      path: '/api/v1/auth/$'
      fullPath: '/api/v1/auth/$'
      preLoaderRoute: typeof ApiV1AuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1WorkspaceRoute: ApiV1WorkspaceRoute,
  ApiV1AuthSplatRoute: ApiV1AuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
